trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseFlutterVersion@0
    inputs:
      version: '3.29.3' # Adjust as needed

  - script: |
      flutter pub get
      flutter analyze
      flutter test
    displayName: 'Install dependencies & run tests'
