trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter --version
    displayName: 'Install Flutter'

  - script: |
      flutter pub get
      flutter analyze
      flutter test
    displayName: 'Build & Test Flutter App'
