// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdo_L4LM5R0m4ZJyl3JNT1egOT7lrhtRs',
    appId: '1:997873925968:web:f836c2596d17e4cf8db655',
    messagingSenderId: '997873925968',
    projectId: 'fir-new-5ff05',
    authDomain: 'fir-new-5ff05.firebaseapp.com',
    storageBucket: 'fir-new-5ff05.firebasestorage.app',
    measurementId: 'G-YL5B08LF4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwcbp-btLQHPwjYp4EQWwc9fIa7VnfUJ8',
    appId: '1:997873925968:android:9aae06180afd3a378db655',
    messagingSenderId: '997873925968',
    projectId: 'fir-new-5ff05',
    storageBucket: 'fir-new-5ff05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7QWkHner-l8GE4eUPPslLdrI9gau1KeQ',
    appId: '1:997873925968:ios:9f188d20530082a98db655',
    messagingSenderId: '997873925968',
    projectId: 'fir-new-5ff05',
    storageBucket: 'fir-new-5ff05.firebasestorage.app',
    androidClientId: '997873925968-0q3andin2jlioqcrkcmf7n6c00g0mkpt.apps.googleusercontent.com',
    iosClientId: '997873925968-s3gemk4vl4l1lk27lmt9jh97oio5u4et.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7QWkHner-l8GE4eUPPslLdrI9gau1KeQ',
    appId: '1:997873925968:ios:9f188d20530082a98db655',
    messagingSenderId: '997873925968',
    projectId: 'fir-new-5ff05',
    storageBucket: 'fir-new-5ff05.firebasestorage.app',
    androidClientId: '997873925968-0q3andin2jlioqcrkcmf7n6c00g0mkpt.apps.googleusercontent.com',
    iosClientId: '997873925968-s3gemk4vl4l1lk27lmt9jh97oio5u4et.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdo_L4LM5R0m4ZJyl3JNT1egOT7lrhtRs',
    appId: '1:997873925968:web:6cfc313ca33025098db655',
    messagingSenderId: '997873925968',
    projectId: 'fir-new-5ff05',
    authDomain: 'fir-new-5ff05.firebaseapp.com',
    storageBucket: 'fir-new-5ff05.firebasestorage.app',
    measurementId: 'G-NYMDPMEKRH',
  );
}
